services:
  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Tallinn
      - SUBDOMAINS=rusparrow
      - TOKEN=0ca270ff-d707-488f-8245-ee132bc94d9c
      - LOG_FILE=true
    volumes:
      - ./duckdns:/config
    restart: unless-stopped
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Tallinn
      - SERVERURL=rusparrow.duckdns.org
      - SERVERPORT=51820
      - PEERS=7
      - PEERDNS=8.8.8.8
      - INTERNAL_SUBNET=10.13.13.0/24
    volumes:
      - ./wireguard:/config
      - /lib/modules:/lib/modules
    ports:
      - "51820:51820/udp"
    restart: unless-stopped
