services:
  web:
    image: nginx:latest
    container_name: mysite
    ports:
      - "8080:80"
    restart: always

  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Tallinn
      - SUBDOMAINS=rusparrow
      - TOKEN=0ca270ff-d707-488f-8245-ee132bc94d9c
      - LOG_FILE=true
    volumes:
      - ./vpn/duckdns:/config
    restart: unless-stopped